"""CLI tool to fit a sway axis from logged camera motion."""

from __future__ import annotations

import argparse
import csv
import numpy as np

from sway_camera.lib.sway_model import (
    SwayModel,
    fit_sway_axis_from_positions,
    save_sway_model_yaml,
)

DEFAULT_OUT = "sway_camera/data/sway_model.yaml"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fit a 3D sway axis from logged motion CSV.")
    parser.add_argument("--csv", required=True, help="CSV generated by motion_logger.py.")
    parser.add_argument("--use-absolute", action="store_true",
                        help="Use absolute X,Y,Z instead of relative dx,dy,dz.")
    parser.add_argument("--min-norm", type=float, default=0.0,
                        help="Minimum vector norm to include a sample (default 0).")
    parser.add_argument("--out", default=DEFAULT_OUT,
                        help=f"Output YAML file for the sway model (default: {DEFAULT_OUT}).")
    return parser.parse_args()


def load_positions(csv_path: str, use_absolute: bool) -> np.ndarray:
    """Load position vectors from the logger CSV."""
    positions = []
    with open(csv_path, "r", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        required = ("X", "Y", "Z", "dx", "dy", "dz")
        missing = [field for field in required if field not in reader.fieldnames]
        if missing:
            raise ValueError(f"CSV is missing columns: {missing}")
        for row in reader:
            if use_absolute:
                vals = [row["X"], row["Y"], row["Z"]]
            else:
                vals = [row["dx"], row["dy"], row["dz"]]
            try:
                arr = np.asarray([float(v) for v in vals], dtype=float)
            except (TypeError, ValueError):
                continue
            if np.any(np.isnan(arr)):
                continue
            positions.append(arr)
    if not positions:
        raise ValueError("No valid samples found in CSV.")
    return np.asarray(positions, dtype=float)


def filter_positions(positions: np.ndarray, min_norm: float) -> np.ndarray:
    """Filter out degenerate samples."""
    if min_norm <= 0:
        return positions
    norms = np.linalg.norm(positions, axis=1)
    mask = norms >= min_norm
    filtered = positions[mask]
    if filtered.size == 0:
        raise ValueError("All samples were filtered out by min_norm.")
    return filtered


def main() -> None:
    args = parse_args()
    positions = load_positions(args.csv, use_absolute=args.use_absolute)
    positions = filter_positions(positions, args.min_norm)

    model: SwayModel = fit_sway_axis_from_positions(positions)
    print(f"[info] Samples used: {positions.shape[0]}")
    print(f"[info] p0 = {model.p0}")
    print(f"[info] d  = {model.d}")

    save_sway_model_yaml(model, args.out)
    print(f"[info] Model saved to {args.out}")


if __name__ == "__main__":
    main()
